#!/bin/sh
#
# File:        ls-machines
# Copyright (C) 2017 TQ Systems GmbH
# @author Markus Niebel <Markus.Niebel@tq-group.com>
#
# Description: build all machines in a layer with a given config
#
# License:     GPLv2
#
###############################################################################
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
###############################################################################

LAYER="meta-tq"

usage() {
	echo "$1 usage:"
	echo "\nlist available machines from layer under sources"
	echo "$1 - use default layer meta-tq"
	echo "$1 <layer name>- use layer given as parameter"
}

main() {
	[ "${#}" -gt "1" ] && usage $0 && return 1
	[ "${#}" -eq "1" ] && LAYER=${1}
	! [ -d "./sources/${LAYER}/conf/machine" ] && usage $0 && return 1

	# filter out machines from the layer 
	TARGETS=$(ls sources/${LAYER}/conf/machine/*.conf | \
		sed s/\.conf//g | xargs -n1 basename)

	echo "Supported machines:"
	for t in ${TARGETS}; do
		echo "\t${t}"
	done

	return 0
}

main $@
