#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2017-2024 TQ-Systems GmbH <oss@ew.tq-group.com>,
# D-82229 Seefeld, Germany.
# Author: Markus Niebel, Martin Schmiedel
#
# Description: build all machines in a layer with a given config
#
###############################################################################
set -e
set -C # noclobber

# TRAP SIGNALS
trap 'error_abort $LINENO' ERR

function error_abort () {
	echo "error at $1"
}

SCRIPTNAME="${0}"
SCRIPTPATH=$(dirname "$(readlink -f "${0}")")
SCRIPT="$(basename "${0}")"
readonly SCRIPTNAME SCRIPTPATH SCRIPT

# depends on bitbake / poky version
readonly BITBAKE_GIT_MIRROR_PKG_EXTENSION="tar.gz"

COMMIT_TIMESTAMP="$(git show --no-patch --pretty='format:%ct' HEAD 2>/dev/null || echo '0')"
readonly COMMIT_TIMESTAMP

. "${SCRIPTPATH}/utils"

usage() {
	cat <<END
Usage:

${SCRIPTNAME} [OPTIONS] <build-dir> <template>

<build-dir>: specifies the build directory location (required)
<template>: template bblayers.conf to use
[-h|--help]: print this message
[--dryrun=<yes|no>]: call bitbake in dry-run mode, default no
[--devel=<yes|no>]: allow development mode, default no, (use different auto.conf to disable CI features)
[--debug=<yes|no>]: print additional informations, default no
[--archive=<yes|no>]: synonym for deploy
[--deploy=<yes|no>]: en/disable deploy, default no
[--deploydir=<directory>]: deploy to this directory (only if --deploy=yes)
[--release=<yes|no>]: en/disable tarball generation, default no, implies deploy=yes
[--skipbitbake=<yes|no>]: don't call bitbake, default no
[--version=<name>]: needed for deploy to generate the version part of archive names
[--machines=<list>]: build only selected machines
[--distros=<list>]: build only selected distros
[--images=<list>]: build only selected targets, usually images

END
}

#
# write common part of build information
#
# (re)create the file, write generic header in Markdown
#
# $1 output file (file to create)
#
create_build_info () {
	local file="${1}"

	# create a file containing information about sources we built from
	cat > "${file}" <<END
# Build information

## Version info for BSP project

### Main project commit

\`\`\`
$(git log -1)
\`\`\`

### Submodules

\`\`\`
$(
	# shellcheck disable=SC2016
	git submodule foreach --quiet 'echo "$name:\n\tURL: $(git remote get-url origin)\n\tREV: $(git log --format="%H" -1) $(git describe --all $(git log --format="%H" -1))"'
)
\`\`\`

END
}

#
# generate build info
#
# $1 output file (file to append)
# $2 bitbake distro
#
print_bitbake_build_info () {
	local file="${1}"
	local distro="${2}"

	cat >> "${file}" <<END

## Configuration info for BSP project

__DISTRO__: ${distro}

### Layer configuration

The following \`bblayers.conf\` template was used in this build:

\`\`\`
$(cat  "$(cat conf/templateconf.cfg)/bblayers.conf.sample")
\`\`\`

END
}

#
# generate machine info
#
# $1 output file (file to append)
# $1 machine name
#
print_bitbake_machine_info () {
	local file="${1}"
	local machine="${2}"

	cat >> "${file}" <<END

## Build target

__MACHINE__: ${machine}

END
}

#
# generate version and source info for a virtual package
#
# Query SRCREV and SRC_URI if there is a provider for the virtual package.
# output the information to the given file. Used for machine specific build
# information. The source must be under version control, e.g. git, to query SRCREV.
#
# $1 output file (file to append)
# $2 target - virtual target to query (e.g. kernel for virtual/kernel)
#
print_virtual_provider_info () {
	local recipe
	recipe=$(bitbake-getvar --quiet --value --ignore-undefined "PREFERRED_PROVIDER_virtual/${2}")
	if [ -n "${recipe}" ] && ! [ "${recipe}" = "None" ]; then
		local srcrev
		local srcuri
		srcrev=$(bitbake-getvar --quiet --value --recipe "${recipe}" --ignore-undefined SRCREV)
		srcuri=$(bitbake-getvar --quiet --value --recipe "${recipe}" --ignore-undefined SRC_URI)
		cat >> "${1}" <<END

### virtual/${2}

__URI__:
\`\`\`
$(for uri in ${srcuri}; do echo "${uri}"; done)
\`\`\`
__COMMIT__:  ${srcrev}
END
	else
		cat >> "${1}" <<END

### virtual/${2}:

No source info available.

END
	fi
}

main () {
	local debug="no"
	local deploy="no"
	local develmode="no"
	local dryrun="no"
	local release="no"
	local skipbitbake="no"
	local build_dir=""
	local build_info_file=""
	local config=""
	local deploydir=""
	local distros=""
	local version="unknown"
	# machine specific packages to deploy, only needed if 'deploy="yes"'
	local -r extra_machine_pkg_for_deploy="kernel-dev kernel-dbg kernel-vmlinux"
	local machines=""
	local images=""
	local pos_params=""
	local stamp=""
	local top_dir=""
	local -a bitbake_args=()

	# default
	deploydir="$(readlink -f ./deployment)"

	while (( "$#" )); do
		case "$1" in
		-h|--help )
			usage
			return 0
			;;
		--archive=* )
			deploy=$(ensure_boolean_arg "${1#*=}") || \
				error_out "Error: invalid option assignment $1, must be boolean"
			shift
			;;
		--debug=* )
			debug=$(ensure_boolean_arg "${1#*=}") || \
				error_out "Error: invalid option assignment $1, must be boolean"
			if [ "${debug}" = "yes" ]; then
				# To enable output from function 'debug' need to set variable
				# 'DEBUG' -  see sourced '${SCRIPTPATH}/utils'
				DEBUG="on"
			fi
			shift
			;;
		--dryrun=* )
			dryrun=$(ensure_boolean_arg "${1#*=}") || \
				error_out "Error: invalid option assignment $1, must be boolean"
			shift
			;;
		--deploy=* )
			deploy=$(ensure_boolean_arg "${1#*=}") || \
				error_out "Error: invalid option assignment $1, must be boolean"
			shift
			;;
		--deploydir=* )
			deploydir="$(readlink -f "${1#*=}")"
			shift
			;;
		--devel=* )
			develmode=$(ensure_boolean_arg "${1#*=}") || \
				error_out "Error: invalid option assignment $1, must be boolean"
			shift
			;;
		--release=* )
			release=$(ensure_boolean_arg "${1#*=}") || \
				error_out "Error: invalid option assignment $1, must be boolean"
			shift
			;;
		--skipbitbake=* )
			skipbitbake=$(ensure_boolean_arg "${1#*=}") || \
				error_out "Error: invalid option assignment $1, must be boolean"
			shift
			;;
		--version=* )
			version=${1#*=}
			shift
			;;
		--distros=* )
			distros=${1#*=}
			shift
			;;
		--machines=* )
			machines=${1#*=}
			shift
			;;
		--images=* )
			images=${1#*=}
			shift
			;;
		--*=|-*) # unsupported flags
			error_out "Error: Unsupported flag $1"
			;;
		*) # preserve positional arguments
			pos_params="$pos_params $1"
			shift
			;;
		esac
	done

	if ! is_gnu_grep; then
		return 1
	fi

	if [ "${dryrun}" = "yes" ]; then
		bitbake_args=('--dry-run')
	fi

	if [ "${release}" = "yes" ] || [ "${deploy}" = "yes" ]; then
		if [ "${dryrun}" = "yes" ] || [ "${skipbitbake}" = "yes " ]; then
			info "Disabling archive/deploy in dry-run / skip-bitbake mode"
			release="no"
			deploy="no"
		fi
	fi

	if [ "${release}" = "yes" ]; then
		info "release/archive implies deploy"
		deploy="yes"
	fi

	# set positional arguments in their proper place
	eval set -- "$pos_params"

	if [ $# -lt 2 ]
	then
		usage
		exit 1
	fi

	build_dir="${1}"
	config="${2}"

	build_info_file="${deploydir}/${config}-build_info.md"
	top_dir="$(pwd)"
	distros="$(get_distros "${top_dir}/${DEFAULT_BUILD_CONFIG}" "${config}" "${distros}")"
	machines="$(get_machines "${top_dir}/${DEFAULT_BUILD_CONFIG}" "${config}" "${machines}")"
	stamp="${version}"

	if [ "${deploy}" = "yes" ]
	then
		# cleanup any old deployment
		if [ -d "${deploydir}" ]; then
			rm -rf "${deploydir}"
		fi
		mkdir -p "${deploydir}"

		info "build and deploy with following version=${stamp}"

		create_build_info "${build_info_file}"
	fi

	debug "Machines to build: ${machines}"
	debug "Distros to build: ${distros}"

	for distro in ${distros}
	do
		# GENERAL
		images=$(get_images "${top_dir}/${DEFAULT_BUILD_CONFIG}" "${distro}" "${images}")
		debug "Images to build: ${images}"

		# source the real setup workhorse
		export DISTRO=${distro}
		export MACHINE
		# TODO: `machines` should always contain one machine per line, so a simple
		# `head -n 1` can be used to get the first one
		MACHINE=$(echo "${machines}" | xargs | awk '{ print $1 }')

		# clean conf, to enforce a really clean configuration and to enable
		# incremental changes in the config using our template dir
		rm -rf "${build_dir}_${distro}/conf"

		# although DISTRO and MACHINE are exported, setup-environment
		# uses these variable mainly to set default in local.conf
		# afterwards they can be set again to iterate over all buildable
		# machines
		if ! . ./setup-environment "${build_dir}_${distro}" "${config}"
		then
			error_out "sourcing setup-environment failed"
		fi

		info "build images"
		#
		# config bitbake from autoconf template
		#
		if [ "${develmode}" = "no" ]
		then
			do_create_auto_conf "ci"
		else
			do_create_auto_conf
		fi

		if [ -n "${SSTATE_DIR}" ]; then
			# add SSTATE dir outside of builddir, optimize global builds
			assign_or_replace SSTATE_DIR "${SSTATE_DIR}" "=" conf/local.conf
		else
			info "env SSTATE_DIR empty, using local dir or add it to your site.conf / auto.conf"
		fi

		if [ -n "${DL_DIR}" ]; then
			# add DL_DIR dir outside of builddir, optimize global builds
			assign_or_replace DL_DIR "${DL_DIR}" "=" conf/local.conf

		else
			info "env DL_DIR empty, using local dir or add it to your site.conf / auto.conf"
		fi

		for img in ${images}
		do
			# now force bitbake to generate images for all targets ...
			for machine in ${machines}
			do
				# overwrite MACHINE
				export MACHINE=${machine}
				# create image for $MACHINE
				info "baking: ${machine} ${distro} ${img} ..."

				if [ "${skipbitbake}" = "no" ]
				then
					if ! bitbake "${bitbake_args[@]}" "${img}"
					then
						error_out "bitbake ${bitbake_args[*]} ${img} for ${MACHINE} failed"
					fi
				fi
			done
		done
		if [ "${deploy}" = "yes" ]
		then
			local distro_codename

			# note: this depends on a selected distro
			distro_codename=$(bitbake-getvar -q --value --ignore-undefined DISTRO_CODENAME)

			for machine in ${machines}; do
				# export $MACHINE before query bitbake
				export MACHINE=${machine}
				local artifact_link_find_opt
				local artifactsdir
				local kernel_dtb
				local kimage
				local machine_archive
				local pkg_deploy_dir
				local pkg_type
				local yocto_machine_dir

				artifactsdir=$(bitbake-getvar -q --value DEPLOY_DIR_IMAGE)
				machine_archive=${machine}_${config}_${distro_codename}_${distro}_${stamp}
				# DEPLOY_DIR_<pkg> depends on PACKAGE_CLASSES, images are built from first type
				# package class names have naming convention 'package_<type>'
				pkg_type=$(bitbake-getvar --quiet --value PACKAGE_CLASSES | awk -F '_' '{ print toupper($2) }')
				pkg_deploy_dir=$(bitbake-getvar --quiet --value "DEPLOY_DIR_${pkg_type}")
				# replace dash with underscore for yocto (default) machine directory name
				yocto_machine_dir=${machine//-/_}
				info "archiving ${machine} ..."
				# we create some files in ${artifactsdir}, clean them before recreate
				rm -f "${artifactsdir}"/*.md
				rm -f "${artifactsdir}"/*.md5sum
				rm -f "${artifactsdir}/${machine_archive}.environment"
				# create a file containing md5sum of files
				get_md5sum "${artifactsdir}" > "${deploydir}/${machine_archive}.md5sum"
				cp "${deploydir}/${machine_archive}.md5sum" "${artifactsdir}/${machine_archive}.md5sum"
				bitbake --environment | grep '^[A-Za-z][^[:space:]]*="' > "${artifactsdir}/${machine_archive}.environment"
				# use pregenerated build info
				cp "${build_info_file}" "${artifactsdir}/${machine_archive}.md"
				# enrich with machine specific information for some virtual packages
				print_bitbake_build_info "${artifactsdir}/${machine_archive}.md" "${distro}"
				print_bitbake_machine_info "${artifactsdir}/${machine_archive}.md" "${machine}"
				print_virtual_provider_info "${artifactsdir}/${machine_archive}.md" kernel
				print_virtual_provider_info "${artifactsdir}/${machine_archive}.md" bootloader
				# TODO:
				# 1) add more packages if needed
				# 2) we have different recipes and use different sources for TF-A / trusted-firmware-a
				# Should atf-imx / qoriq-atf etc. labeled as PREFERRED_PROVIDER? If yes, this should go upstream.
				# print_virtual_provider_info "${artifactsdir}/${machine_archive}.info" "trusted-firmware-a"

				# add some artifacts for automated testing, needed by name / pattern without
				# bitbake timestamp annotation etc. Copy the named links as file. Real files
				# will be copied after this.
				mkdir -p "${deploydir}/${machine}"

				# options to find and copy links as artifacts for CI testing
				local -a artifact_link_find_opt=(-type l -readable)
				# deploy rootfs tar.gz image if existing. Use ${IMAGE_LINK_NAME} plus 'tar.gz'
				# to decouple bitbake / YP and our test jobs expecting rootfs artifacts as
				# '${image-recipe-name}-${machine}.tar.gz'
				for img in ${images}; do
					local image_name

					image_name=$(bitbake-getvar --recipe "${img}" --quiet --value --ignore-undefined IMAGE_LINK_NAME)
					find "${artifactsdir}" -maxdepth 1 -name "${image_name}.tar.gz" "${artifact_link_find_opt[@]}" \
						-exec cp --dereference "{}" "${deploydir}/${machine}/${img}-${machine}.tar.gz" \;
				done

				# deploy kernel device tree if existing
				kernel_dtb=$(bitbake-getvar --recipe virtual/kernel --quiet --value --ignore-undefined KERNEL_DEVICETREE)
				for dtb in ${kernel_dtb}; do
					find "${artifactsdir}" -maxdepth 1 -name "$(basename "${dtb}")" "${artifact_link_find_opt[@]}" \
						-exec cp "{}" "${deploydir}/${machine}/" \;
				done
				# deploy the kernel image if existing
				kimage=$(bitbake-getvar --recipe virtual/kernel --quiet --value --ignore-undefined KERNEL_IMAGETYPES)
				for image in ${kimage}; do
					find "${artifactsdir}" -maxdepth 1 -name "${image}" "${artifact_link_find_opt[@]}" \
						-exec cp "{}" "${deploydir}/${machine}/" \;
				done

				# device tree and dev package, exact pattern for version depends on $pkg_type
				for pkg in ${extra_machine_pkg_for_deploy}; do
					find "${pkg_deploy_dir}/${yocto_machine_dir}" -maxdepth 1 -name "${pkg}-*" -readable \
						-exec cp "{}" "${deploydir}/${machine}/" \;
				done

				# copy rest of artifact files but do not override existing files which could be
				# needed for test
				find "${artifactsdir}" -type f -print0 | \
					xargs --null --no-run-if-empty cp --no-clobber --target-directory="${deploydir}/${machine}/"

				if [ "${release}" = "yes" ]
				then
					local download_dir
					local archive_basename
					local download_sources
					local archived_sources
					local combined_sources
					declare -a tar_options=(
						--numeric-owner --owner=0 --group=0
						--sort=name --mtime="@${COMMIT_TIMESTAMP}"
						--use-compress-program='pigz -nm'
					)

					archive_basename=${deploydir}/${machine_archive}

					# create image archive for $MACHINE, assume DEPLOY_DIR_IMAGE has ${MACHINE} as final part
					if ! tar -cvf "${archive_basename}.BIN.tar.gz" \
						-C "$(dirname "${artifactsdir}")" \
						"$(basename "${artifactsdir}")" "${tar_options[@]}"
					then
						error_out "archiving for ${machine} failed"
					fi

					# create licenses and mirror archive
					mkdir -p "${archive_basename}.LIC"
					# copy the file from licenses
					# using LICENSE_DIRECTORY be the correct way but if we use BBMULTICONFIG
					# there may be different values for LICENSE_DIRECTORY for one machine build
					# this is the case for TI based SoC with k3r5
					find . -type d -maxdepth 4 -wholename "*tmp*/deploy/licenses/*" -print0 | \
						xargs --null --no-run-if-empty cp --recursive \
						--target-directory="${archive_basename}.LIC/"

					tar -cvf "${archive_basename}.LIC.tar.gz" \
						--directory "$(dirname "${archive_basename}.LIC")" \
						"$(basename "${archive_basename}.LIC")" \
						"${tar_options[@]}"

					# do some cleanup
					rm -rf "${archive_basename}.LIC"

					mkdir -p "${archive_basename}.MIRROR.SRC"
					download_dir=$(bitbake-getvar -q --value DL_DIR)
					# query all archived sources, needs archiver class in config
					archived_sources=$(find . -wholename "*tmp*/deploy/sources/*/*/*" -printf "%f\n" | sort)

					# copy the file from archived sources if it exists in download_dir
					download_sources=$(find "${download_dir}" -printf "%f\n" | sort)
					combined_sources=$(comm -12 <(echo "$archived_sources") <(echo "$download_sources"))
					echo "$combined_sources" | xargs -I%  cp "${download_dir}/%" "${archive_basename}.MIRROR.SRC" --dereference

					# we assume here that bitbake is configured to use shallow cloning
					# and that these packages use ${BITBAKE_GIT_MIRROR_PKG_EXTENSION} as extension
					find "${download_dir}" -name "gitshallow_*.${BITBAKE_GIT_MIRROR_PKG_EXTENSION}" -print0 | \
						xargs --null --no-run-if-empty cp --no-clobber --target-directory="${archive_basename}.MIRROR.SRC/"
					find "${download_dir}" -name "gitsmshallow_*.${BITBAKE_GIT_MIRROR_PKG_EXTENSION}" -print0 | \
						xargs --null --no-run-if-empty cp --no-clobber --target-directory="${archive_basename}.MIRROR.SRC/"

				fi
				# TODO: linking ${artifactsdir} to ${deploydir}/${machine} only works for fresh
				# checkout as used in a CI environment
			done
		fi

		cd "${top_dir}"
	done
}

main "${@}"
