#!/bin/sh
#
# File:        ls-configs
# Copyright (C) 2022 TQ-Systems GmbH
# @author Markus Niebel <Markus.Niebel@tq-group.com>
#
# Description: list all configs in buildspace
#
# License:     GPLv2
#
###############################################################################
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
###############################################################################

readonly DEFAULT_TEMPLATEDIR="template"

usage() {
	echo "$1 usage:"
	echo "\nlist available configs from template dir under sources"
	echo "$1 - use default template dir ${DEFAULT_TEMPLATEDIR}"
	echo "$1 <template> - use template dir given as parameter"
}

main() {
	local TEMPLATEDIR=${DEFAULT_TEMPLATEDIR}

	if [ "${#}" -gt "1" ]; then
		usage "$0"
		return 1
	fi

	if [ "${#}" -eq "1" ]; then
		TEMPLATEDIR="${1}"
	fi

	if ! [ -d "./sources/${TEMPLATEDIR}/conf" ]; then
		usage "$0"
		return 1
	fi

	# filter out configs from the template dir
	local EXCLUDE="bblayers.conf.sample"
	local CONFIGURATIONS="$(ls -1 sources/${TEMPLATEDIR}/conf/bblayers.conf.* |
		xargs -n1 basename)"
	CONFIGURATIONS=$(echo "${CONFIGURATIONS}" | grep -vxF "${EXCLUDE}")
	for c in ${CONFIGURATIONS}; do
		echo "${c##*.}"
	done

	return 0
}

main "$@"
