#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later
#
# File:        ls-distros
# Copyright (C) 2022 TQ-Systems GmbH
# @author Markus Niebel <Markus.Niebel@tq-group.com>
#
# Description: list all distros in a layer
#
###############################################################################

readonly DEFAULT_LAYER="meta-tq/meta-dumpling"

usage() {
	echo "$1 usage:"
	echo "\nlist available distros from layer under sources"
	echo "$1 - use default layer ${DEFAULT_LAYER}"
	echo "$1 <layer name>- use layer given as parameter"
}

main() {
	local LAYER=${DEFAULT_LAYER}

	if [ "${#}" -gt "1" ]; then
		usage "$0"
		return 1
	fi

	if [ "${#}" -eq "1" ]; then
		LAYER="${1}"
	fi

	if ! [ -d "./sources/${LAYER}/conf/distro" ]; then
		usage "$0"
		return 1
	fi

	# filter out machines from the layer
	TARGETS=$(ls sources/${LAYER}/conf/distro/*.conf | \
		sed s/\.conf//g | xargs -n1 basename)

	for t in ${TARGETS}; do
		echo "${t}"
	done

	return 0
}

main "$@"
