#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2022-2023 TQ-Systems GmbH <oss@ew.tq-group.com>,
# D-82229 Seefeld, Germany.
# Author: Markus Niebel
#
# Description: list all distros in a layer
#
###############################################################################

set -e
set -C # noclobber

# TRAP SIGNALS
trap 'error_abort $LINENO' ERR

function error_abort () {
	echo "error at $1"
}

readonly DEFAULT_LAYER="meta-tq/meta-dumpling"
readonly SCRIPT="$(basename "${0}")"

usage() {
	cat <<END
${1} usage:

list available distros from layer under sources
${1} - use default layer ${DEFAULT_LAYER}
${1} <layer name>- use layer given as parameter
END
}

main() {
	if [ "${#}" -gt "1" ]; then
		usage "${SCRIPT}"
		return 1
	fi

	local LAYER=${1:-${DEFAULT_LAYER}}

	if ! [ -d "./sources/${LAYER}/conf/distro" ]; then
		usage "${SCRIPT}"
		return 1
	fi

	# filter out distros from the layer
	TARGETS=$(ls sources/${LAYER}/conf/distro/*.conf | \
		sed s/\.conf//g | xargs -n1 basename)

	for t in ${TARGETS}; do
		echo "${t}"
	done

	return 0
}

main "$@"
