#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
#
# File:        ls-machines
#
# Copyright (C) 2017-2023 TQ-Systems GmbH <oss@ew.tq-group.com>,
# D-82229 Seefeld, Germany.
# Author: Markus Niebel
#
# Description: list all machines in a layer
#
###############################################################################

set -e
set -C # noclobber

# TRAP SIGNALS
trap 'error_abort $LINENO' ERR

function error_abort () {
	echo "error at $1"
}

readonly DEFAULT_LAYER="meta-tq/meta-tq"
readonly SCRIPT="$(basename "${0}")"

usage() {
	cat <<END
${1} usage:

list available machines from layer under sources
${1} - use default layer ${DEFAULT_LAYER}
${1} <layer name>- use layer given as parameter
END
}

main() {
	if [ "${#}" -gt "1" ]; then
		usage "${SCRIPT}"
		return 1
	fi

	local LAYER=${1:-${DEFAULT_LAYER}}

	if ! [ -d "./sources/${LAYER}/conf/machine" ]; then
		usage "${SCRIPT}"
		return 1
	fi

	# filter out machines from the layer
	TARGETS=$(ls sources/${LAYER}/conf/machine/*.conf | \
		sed s/\.conf//g | xargs -n1 basename)

	for t in ${TARGETS}; do
		echo "${t}"
	done

	return 0
}

main "$@"
