#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
#
# File:        ls-machines
#
# Copyright (C) 2017-2023 TQ-Systems GmbH <oss@ew.tq-group.com>,
# D-82229 Seefeld, Germany.
# Author: Markus Niebel
#
# Description: list all machines in a layer
#
###############################################################################

set -e
set -C # noclobber

# TRAP SIGNALS
trap 'error_abort $LINENO' ERR

function error_abort () {
	echo "error at $1"
}

readonly DEFAULT_LAYER="meta-tq/meta-tq"

usage() {
	echo "$1 usage:"
	echo "\nlist available machines from layer under sources"
	echo "$1 - use default layer ${DEFAULT_LAYER}"
	echo "$1 <layer name>- use layer given as parameter"
}

main() {
	local LAYER=${DEFAULT_LAYER}

	if [ "${#}" -gt "1" ]; then
		usage "$0"
		return 1
	fi

	if [ "${#}" -eq "1" ]; then
		LAYER="${1}"
	fi

	if ! [ -d "./sources/${LAYER}/conf/machine" ]; then
		usage "$0"
		return 1
	fi

	# filter out machines from the layer
	TARGETS=$(ls sources/${LAYER}/conf/machine/*.conf | \
		sed s/\.conf//g | xargs -n1 basename)

	for t in ${TARGETS}; do
		echo "${t}"
	done

	return 0
}

main "$@"
